apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  generation: 1
  labels:
    strimzi.io/cluster: my-cluster
  name: broker
  namespace: streams-kafka
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral