apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: console-user
  namespace: streams-kafka
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: kafka-user-password
          key: kafka-user-password
  authorization:
    acls:
      - operations:
          - Read
          - Write
          - Describe
          - Create
          - Delete
          - Alter
          - DescribeConfigs
          - AlterConfigs
        resource:
          name: '*'
          patternType: literal
          type: topic
      - operations:
          - Read
          - Describe
        resource:
          name: '*'
          patternType: literal
          type: group
      - operations:
          - Create
          - Describe
          - Alter
          - IdempotentWrite
        resource:
          type: cluster
      - operations:
          - Describe
          - Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    type: simple
